networks:
   vinyanext:
      driver: bridge
      ipam:
         config:
            - subnet: 10.10.0.0/24

services:
   vynpostgresql:
      image: postgres:17.4
      container_name: vynpostgresql
      ports:
         - "5432:5432"
      volumes:
         - ./data/postgresql/data:/var/lib/postgresql/data
         - ./config/postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh
         - ./config/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
         - ./config/postgresql/script-vinyanext-01-table.sql:/docker-entrypoint-initdb.d/script-vinyanext-01-table.sql
      environment:
         POSTGRES_PASSWORD: admin#2025
      networks:
         vinyanext:
            ipv4_address: 10.10.0.10
   vynseq:
      image: datalust/seq:2025.1.13956-pre
      container_name: vynseq
      ports:
         - 8081:80
         - 5341:5341
      volumes:
         - ./data/seq/data:/data
      environment:
         ACCEPT_EULA: Y
      networks:
         vinyanext:
            ipv4_address: 10.10.0.20
   vynmongo:
      image: mongo:8.0.10-rc0-noble
      container_name: vynmongo
      ports:
         - 27017:27017
      volumes:
         - ./data/mongo/data:/data/db
         - ./data/mongo/configdb:/data/configdb
      environment:
         MONGO_INITDB_DATABSE: vinyanext
         MONGO_INITDB_ROOT_USERNAME: vyn
         MONGO_INITDB_ROOT_PASSWORD: admin#2025
      networks:
         vinyanext:
            ipv4_address: 10.10.0.30
   vynredis:
      image: redis:8.0.1
      container_name: vynredis
      ports:
         - 6379:6379
      volumes:
         - ./config/redis:/usr/local/etc/redis
         - ./data/redis/data:/data
      command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
      networks:
         vinyanext:
            ipv4_address: 10.10.0.40
