networks:
   vinyanext:
      driver: bridge
      ipam:
         config:
            - subnet: 10.10.0.0/24
  
services:
   vynpostgresql:
      image: postgres:17.4
      container_name: vynpostgresql
      ports:
         - "5432:5432"
      volumes:
         - ./data/postgresql/data:/var/lib/postgresql/data
         - ./config/postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh
         - ./config/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
         POSTGRES_PASSWORD: admin@2025
      networks:
         vinyanext:
            ipv4_address: 10.10.0.10
   vynseq:
      image: datalust/seq:2025.1.13956-pre
      container_name: vynseq
      environment:
         - ACCEPT_EULA=Y
      ports:
         - 8081:80
         - 5341:5341
      volumes:
         - ./data/seq/data:/data
      networks:
         vinyanext:
            ipv4_address: 10.10.0.11